services:
  worker1_ventas:    
    image: workers
    container_name: Worker1_Ventas
    networks: 
      - red_Ventas
    restart: always
    ports:
      - "1631:631"

  worker2_ventas:    
    image: workers
    container_name: Worker2_Ventas
    networks: 
      - red_Ventas
    restart: always
    ports:
      - "1632:631"

  worker3_ventas:    
    image: workers
    container_name: Worker3_Ventas
    networks: 
      - red_Ventas
    restart: always
    ports:
      - "1633:631"
  
  worker4_ventas:    
    image: workers
    container_name: Worker4_Ventas
    networks: 
      - red_Ventas
    restart: always
    ports:
      - "1634:631"
  
  worker5_ventas:    
    image: workers
    container_name: Worker5_Ventas
    networks: 
      - red_Ventas
    restart: always
    ports:
      - "1635:631"
  
  impresora1_ventas:
    image: printers
    container_name: Impresora1_Ventas
    networks:
      - red_Ventas
    restart: always
    ports:
      - "1660:631"

  impresora2_ventas:
    image: printers
    container_name: Impresora2_Ventas
    networks:
      - red_Ventas
    restart: always
    ports:
      - "1661:631"

  worker1_soporte:    
    image: workers
    container_name: Worker1_Soporte
    networks: 
      - red_Soporte
    restart: always
    ports:
      - "1636:631"

  worker2_soporte:
    image: workers
    container_name: Worker2_Soporte
    networks:
      - red_Soporte
    restart: always
    ports:
      - "1637:631"

  worker3_soporte:
    image: workers
    container_name: Worker3_Soporte
    networks: 
      - red_Soporte
    restart: always
    ports:
      - "1638:631"

  worker4_soporte:
    image: workers
    container_name: Worker4_Soporte
    networks: 
      - red_Soporte
    restart: always
    ports:
      - "1639:631"

  worker5_soporte:
    image: workers
    container_name: Worker5_Soporte
    networks:
      - red_Soporte
    restart: always
    ports:
      - "1640:631"

  worker1_conta:
    image: workers
    container_name: Worker1_Contabilidad
    networks:
      - red_Contabilidad
    restart: always
    ports:
      - "1641:631"

  worker2_conta:
    image: workers
    container_name: Worker2_Contabilidad
    networks:
      - red_Contabilidad
    restart: always
    ports:
      - "1642:631"

  worker3_conta:
    image: workers
    container_name: Worker3_Contabilidad
    networks: 
      - red_Contabilidad
    restart: always
    ports:
      - "1643:631"

  worker4_conta:
    image: workers
    container_name: Worker4_Contabilidad
    networks: 
      - red_Contabilidad
    restart: always
    ports:
      - "1644:631"

  worker5_conta:
    image: workers
    container_name: Worker5_Contabilidad
    networks:
      - red_Contabilidad
    restart: always
    ports:
      - "1645:631"

  worker1_gerencia:
    image: workers
    container_name: Worker1_Gerencia
    networks:
      - red_Gerencia
    restart: always
    ports:
      - "1646:631"

  worker2_gerencia:
    image: workers
    container_name: Worker2_Gerencia
    networks:
      - red_Gerencia
    restart: always
    ports:
      - "1647:631"

  worker3_gerencia:
    image: workers
    container_name: Worker3_Gerencia
    networks:
      - red_Gerencia
    restart: always
    ports:
      - "1648:631"

  worker4_gerencia:
    image: workers
    container_name: Worker4_Gerencia
    networks:
      - red_Gerencia
    restart: always
    ports:
      - "1649:631"

  worker5_gerencia:
    image: workers
    container_name: Worker5_Gerencia
    networks:
      - red_Gerencia
    restart: always
    ports:
      - "1650:631"

  worker1_recursos:
    image: workers
    container_name: Worker1_RecursosHumanos
    networks:
      - red_RecursosHumanos
    restart: always
    ports:
      - "1651:631"

  worker2_recursos:
    image: workers
    container_name: Worker2_RecursosHumanos
    networks:
      - red_RecursosHumanos
    restart: always
    ports:
      - "1652:631"

  worker3_recursos:
    image: workers
    container_name: Worker3_RecursosHumanos
    networks:
      - red_RecursosHumanos
    restart: always
    ports:
      - "1653:631"

  worker4_recursos:
    image: workers
    container_name: Worker4_RecursosHumanos
    networks:
      - red_RecursosHumanos
    restart: always
    ports:
      - "1654:631"

  worker5_recursos:
    image: workers
    container_name: Worker5_RecursosHumanos
    networks:
      - red_RecursosHumanos
    restart: always
    ports:
      - "1655:631"

networks:
  red_Ventas:
    ipam:
      driver: default
      config:
        - subnet: "192.168.1.0/28"
  red_Soporte:    
    ipam:
      driver: default
      config:
        - subnet: "192.168.1.16/28"
  red_Contabilidad:    
    ipam:
      driver: default
      config:
        - subnet: "192.168.1.32/28"
  red_Gerencia:
    ipam:
      driver: default
      config:
        - subnet: "192.168.1.48/28"
  red_RecursosHumanos:
    ipam:
      driver: default
      config:
        - subnet: "192.168.1.64/28"

