services:

  sambabackup:
    image: backupservice
    container_name: SambaBackup
    networks:
      - red_Admin
    volumes:
      - samba_backups:/backup
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined
    privileged: true  
    restart: always
    ports:
      - "8000:8000"


  sambaserver:
    image: dperson/samba
    container_name: SambaServer
    networks:
      - red_Admin
      - red_Ventas
      - red_Soporte
      - red_Gerencia
      - red_Contabilidad
      - red_RecursosHumanos
    volumes:
      - ./sambaserver/shared_data:/shared
    command: >
      -u "smbuser;smbpass" 
      -s "shared;/shared;yes;no;no;smbuser"
    restart: always


  mailserver:
    image: mailserver/docker-mailserver
    container_name: mailserver
    hostname: "mailserver" 
    domainname: "lol.com"
    networks:
      red_RecursosHumanos:
      red_Ventas:
      red_Soporte:
      red_Gerencia:
      red_Contabilidad:
      red_Admin:
    restart: always
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    environment:
      - ENABLE_SPAMASSASSIN=1
      - SPAMASSASSIN_SPAM_TO_INBOX=1
      - ENABLE_CLAMAV=1
      - ENABLE_POSTGREY=1
      - ENABLE_FAIL2BAN=0
      - ENABLE_SASLAUTHD=1
      - ONE_DIR=1
      - TZ=America/New_York
    volumes:
      - ./mailserver/data/:/var/mail/
      - ./mailserver/state/:/var/mail-state/
      - ./mailserver/logs/:/var/log/mail/
      - ./mailserver/config/:/tmp/docker-mailserver/


  worker1_ventas:    
    image: workers_ventas
    container_name: Worker1_Ventas
    networks: 
      - red_Ventas
    restart: always
    ports:
      - "1631:631"

  worker2_ventas:    
    image: workers_ventas
    container_name: Worker2_Ventas
    networks: 
      - red_Ventas
    restart: always
    ports:
      - "1632:631"

  worker3_ventas:    
    image: workers_ventas
    container_name: Worker3_Ventas
    networks: 
      - red_Ventas
    restart: always
    ports:
      - "1633:631"
  
  worker4_ventas:    
    image: workers_ventas
    container_name: Worker4_Ventas
    networks: 
      - red_Ventas
    restart: always
    ports:
      - "1634:631"
  
  worker5_ventas:    
    image: workers_ventas
    container_name: Worker5_Ventas
    networks: 
      - red_Ventas
    restart: always
    ports:
      - "1635:631"
  
  impresora1_ventas:
    image: printers
    container_name: Impresora1_Ventas
    networks:
      - red_Ventas
    restart: always
    ports:
      - "1660:631"

  impresora2_ventas:
    image: printers
    container_name: Impresora2_Ventas
    networks:
      - red_Ventas
    restart: always
    ports:
      - "1661:631"

  worker1_soporte:    
    image: workers_soporte
    container_name: Worker1_Soporte
    networks: 
      - red_Soporte
    restart: always
    ports:
      - "1636:631"

  worker2_soporte:
    image: workers_soporte
    container_name: Worker2_Soporte
    networks:
      - red_Soporte
    restart: always
    ports:
      - "1637:631"

  worker3_soporte:
    image: workers_soporte
    container_name: Worker3_Soporte
    networks: 
      - red_Soporte
    restart: always
    ports:
      - "1638:631"

  worker4_soporte:
    image: workers_soporte
    container_name: Worker4_Soporte
    networks: 
      - red_Soporte
    restart: always
    ports:
      - "1639:631"

  worker5_soporte:
    image: workers_soporte
    container_name: Worker5_Soporte
    networks:
      - red_Soporte
    restart: always
    ports:
      - "1640:631"

  impresora1_soporte:
    image: printers
    container_name: Impresora1_Soporte
    networks:
      - red_Soporte
    restart: always
    ports:
      - "1662:631"

  impresora2_soporte:
    image: printers
    container_name: Impresora2_Soporte
    networks:
      - red_Soporte
    restart: always
    ports:
      - "1663:631"

  worker1_conta:
    image: workers_contabilidad
    container_name: Worker1_Contabilidad
    networks:
      - red_Contabilidad
    restart: always
    ports:
      - "1641:631"

  worker2_conta:
    image: workers_contabilidad
    container_name: Worker2_Contabilidad
    networks:
      - red_Contabilidad
    restart: always
    ports:
      - "1642:631"

  worker3_conta:
    image: workers_contabilidad
    container_name: Worker3_Contabilidad
    networks: 
      - red_Contabilidad
    restart: always
    ports:
      - "1643:631"

  worker4_conta:
    image: workers_contabilidad
    container_name: Worker4_Contabilidad
    networks: 
      - red_Contabilidad
    restart: always
    ports:
      - "1644:631"

  worker5_conta:
    image: workers_contabilidad
    container_name: Worker5_Contabilidad
    networks:
      - red_Contabilidad
    restart: always
    ports:
      - "1645:631"

  impresora1_conta:
    image: printers
    container_name: Impresora1_Contabilidad
    networks:
      - red_Contabilidad
    restart: always
    ports:
      - "1664:631"

  impresora2_conta:
    image: printers
    container_name: Impresora2_Contabilidad
    networks:
      - red_Contabilidad
    restart: always
    ports:
      - "1665:631"

  worker1_gerencia:
    image: workers_gerencia
    container_name: Worker1_Gerencia
    networks:
      - red_Gerencia
    restart: always
    ports:
      - "1646:631"

  worker2_gerencia:
    image: workers_gerencia
    container_name: Worker2_Gerencia
    networks:
      - red_Gerencia
    restart: always
    ports:
      - "1647:631"

  worker3_gerencia:
    image: workers_gerencia
    container_name: Worker3_Gerencia
    networks:
      - red_Gerencia
    restart: always
    ports:
      - "1648:631"

  worker4_gerencia:
    image: workers_gerencia
    container_name: Worker4_Gerencia
    networks:
      - red_Gerencia
    restart: always
    ports:
      - "1649:631"

  worker5_gerencia:
    image: workers_gerencia
    container_name: Worker5_Gerencia
    networks:
      - red_Gerencia
    restart: always
    ports:
      - "1650:631"

  impresora1_gerencia:
    image: printers
    container_name: Impresora1_Gerencia
    networks:
      - red_Gerencia
    restart: always
    ports:
      - "1666:631"

  impresora2_gerencia:
    image: printers
    container_name: Impresora2_Gerencia
    networks:
      - red_Gerencia
    restart: always
    ports:
      - "1667:631"

  worker1_recursos:
    image: workers_recursos
    container_name: Worker1_RecursosHumanos
    networks:
      - red_RecursosHumanos
    restart: always
    ports:
      - "1651:631"

  worker2_recursos:
    image: workers_recursos
    container_name: Worker2_RecursosHumanos
    networks:
      - red_RecursosHumanos
    restart: always
    ports:
      - "1652:631"

  worker3_recursos:
    image: workers_recursos
    container_name: Worker3_RecursosHumanos
    networks:
      - red_RecursosHumanos
    restart: always
    ports:
      - "1653:631"

  worker4_recursos:
    image: workers_recursos
    container_name: Worker4_RecursosHumanos
    networks:
      - red_RecursosHumanos
    restart: always
    ports:
      - "1654:631"

  worker5_recursos:
    image: workers_recursos
    container_name: Worker5_RecursosHumanos
    networks:
      - red_RecursosHumanos
    restart: always
    ports:
      - "1655:631"

  impresora1_recursos:
    image: printers
    container_name: Impresora1_RecursosHumanos
    networks:
      - red_RecursosHumanos
    restart: always
    ports:
      - "1668:631"

  impresora2_recursos:
    image: printers
    container_name: Impresora2_RecursosHumanos
    networks:
      - red_RecursosHumanos
    restart: always
    ports:
      - "1669:631"

  adminred:
    image: admin
    container_name: adminred
    hostname: adminred
    networks:
      - red_RecursosHumanos
      - red_Ventas
      - red_Soporte
      - red_Gerencia
      - red_Contabilidad
      - red_Admin
    volumes:
      - ./mailserver/config:/mail-config
    tty: true
    stdin_open: true

networks:

  red_Ventas:
    ipam:
      driver: default
      config:
        - subnet: "192.168.1.0/28"

  red_Soporte:    
    ipam:
      driver: default
      config:
        - subnet: "192.168.1.16/28"

  red_Contabilidad:    
    ipam:
      driver: default
      config:
        - subnet: "192.168.1.32/28"

  red_Gerencia:
    ipam:
      driver: default
      config:
        - subnet: "192.168.1.48/28"

  red_RecursosHumanos:
    ipam:
      driver: default
      config:
        - subnet: "192.168.1.64/28"

  red_Admin:
    ipam:
      driver: default
      config:
        - subnet: "192.168.1.80/28"

volumes:
  samba_backups:
